documents:
- features:
    has_bibliography: false
    has_cover: false
    has_toc: false
  lang:
  - FR
  - EN
  settings:
    color: blue
  template: templates/cv_skeleton.tex
  type: CV
- features:
    has_bibliography: false
    has_cover: false
    has_toc: false
  lang:
  - FR
  - EN
  - DE
  recipient: Hiring Manager
  sections:
  - file: templates/sections/letter_body.tex
  template: templates/letter_skeleton.tex
  type: Letter
